#配置数据源
spring:
  datasource:
    url: jdbc:p6spy:mysql://rm-uf6k2sr7a43o06xe2.mysql.rds.aliyuncs.com:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    username: piaohao
    password: PIAOhao191@

p6spy:
  config:
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime)| 执行sql:%(sqlSingleLine)
    driverlist: com.mysql.cj.jdbc.Driver